// File: frontend/next-env.d.ts
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: Do not add any other lines to this file!
// This file is automatically generated by Next.js.
// You should not modify it.
