"""Add chat history tables

Revision ID: 0667723e0730
Revises: 3a29a097cb45
Create Date: 2025-10-20 08:34:55.131223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0667723e0730'
down_revision: Union[str, Sequence[str], None] = '3a29a097cb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.create_foreign_key(None, 'bookings', 'destinations', ['pickup_destination_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'destinations', ['dropoff_destination_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'faqs', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pricing', 'destinations', ['to_destination_id'], ['id'])
    op.create_foreign_key(None, 'pricing', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pricing', 'destinations', ['from_destination_id'], ['id'])
    op.create_foreign_key(None, 'pricing', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'service_features', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'service_vehicles', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'service_vehicles', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_vehicles', type_='foreignkey')
    op.drop_constraint(None, 'service_vehicles', type_='foreignkey')
    op.drop_constraint(None, 'service_features', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'faqs', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_table('chat_sessions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('itinerary', mysql.JSON(), nullable=True),
    sa.Column('customization_request', mysql.JSON(), nullable=True),
    sa.Column('booking_summary_itinerary', mysql.JSON(), nullable=True),
    sa.Column('ride_details', mysql.JSON(), nullable=True),
    sa.Column('auth_prompt', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###
