"""Consolidate user table updates for 2fa and timezones

Revision ID: 3a29a097cb45
Revises: abd1c91c7158
Create Date: 2025-10-15 14:24:12.322175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a29a097cb45'
down_revision: Union[str, Sequence[str], None] = 'abd1c91c7158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bookings', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'destinations', ['dropoff_destination_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'destinations', ['pickup_destination_id'], ['id'])
    op.create_foreign_key(None, 'faqs', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pricing', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pricing', 'destinations', ['to_destination_id'], ['id'])
    op.create_foreign_key(None, 'pricing', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pricing', 'destinations', ['from_destination_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'service_features', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'service_vehicles', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'service_vehicles', 'vehicles', ['vehicle_id'], ['id'])
    op.alter_column('users', 'two_factor_secret',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               type_=sa.String(length=191),
               existing_nullable=True)
    op.create_unique_constraint(None, 'users', ['two_factor_secret'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'two_factor_secret',
               existing_type=sa.String(length=191),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'service_vehicles', type_='foreignkey')
    op.drop_constraint(None, 'service_vehicles', type_='foreignkey')
    op.drop_constraint(None, 'service_features', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'faqs', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    # ### end Alembic commands ###
