"""Add timestamps and status to users table

Revision ID: 9e5243bd3bd5
Revises: e1b80f3d6a44
Create Date: 2025-10-15 11:10:32.196229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5243bd3bd5'
down_revision: Union[str, Sequence[str], None] = 'e1b80f3d6a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bookings', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'destinations', ['pickup_destination_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'destinations', ['dropoff_destination_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'faqs', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pricing', 'destinations', ['from_destination_id'], ['id'])
    op.create_foreign_key(None, 'pricing', 'destinations', ['to_destination_id'], ['id'])
    op.create_foreign_key(None, 'pricing', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pricing', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'service_features', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'service_vehicles', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'service_vehicles', 'services', ['service_id'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'service_vehicles', type_='foreignkey')
    op.drop_constraint(None, 'service_vehicles', type_='foreignkey')
    op.drop_constraint(None, 'service_features', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'faqs', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    # ### end Alembic commands ###
