"""Add reset code fields to users

Revision ID: abd1c91c7158
Revises: 802f6da87b16
Create Date: 2025-10-15 13:48:05.615042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd1c91c7158'
down_revision: Union[str, Sequence[str], None] = '802f6da87b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bookings', 'destinations', ['dropoff_destination_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'destinations', ['pickup_destination_id'], ['id'])
    op.create_foreign_key(None, 'faqs', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pricing', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pricing', 'destinations', ['to_destination_id'], ['id'])
    op.create_foreign_key(None, 'pricing', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pricing', 'destinations', ['from_destination_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'service_features', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'service_vehicles', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'service_vehicles', 'vehicles', ['vehicle_id'], ['id'])
    op.add_column('users', sa.Column('password_reset_code', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_code_expires_at')
    op.drop_column('users', 'password_reset_code')
    op.drop_constraint(None, 'service_vehicles', type_='foreignkey')
    op.drop_constraint(None, 'service_vehicles', type_='foreignkey')
    op.drop_constraint(None, 'service_features', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_constraint(None, 'faqs', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    # ### end Alembic commands ###
